### ISSUE TITLE
Crear Modelo de Convenios Crud

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/convenios_crud#1]
- [x] basado en la reunión grupal crear un modelo de base de datos.
**calidad**
- [x] modelo es discutido y aprobado

**Comment by fabianbarreto02** [comment]
![modelo_propuesto](https://user-images.githubusercontent.com/43799065/58647811-f44b6880-82cd-11e9-9bdd-536c8bebb5f1.jpg)

**Comment by fabianbarreto02** [comment]
![convenio](https://user-images.githubusercontent.com/43799065/58647881-1ba23580-82ce-11e9-8eda-01e1739bfe27.png)

**Comment by fabianbarreto02** [comment]
[convenio.dbm.zip](https://github.com/udistrital/convenios_crud/files/3237868/convenio.dbm.zip)

**Comment by fabianbarreto02** [comment]
[convenio.sql.zip](https://github.com/udistrital/convenios_crud/files/3241720/convenio.sql.zip)

**Comment by Soulfilip-UD** [comment]
Modelo aprobado, documentado Se cierra el Issue
